### ISSUE TITLE
IEDriverServer.exe 3.9.0.0 is detected as SONAR.Heuristic by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by KevinChrz** [jsakamoto/nupkg-selenium-webdriver-iedriver#10]
As of February 2, 2018 the file IEDriverServer.exe is flagging with Norton Symantec Endpoint Protection as Heur.AdvML.C with the following details:

Category: Malware
Sub category: Heuristic Virus
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: Heur.AdvML.C
File: C:\PATHING\packages\Selenium.WebDriver.IEDriver.3.9.0\driver\IEDriverServer.exe
Location: Deleted or access blocked
Computer: 
User: NETWORK SERVICE
Action taken: Cleaned by Deletion

![iedriverserver flag 01](https://user-images.githubusercontent.com/13453819/36555163-30244cca-17cf-11e8-9c35-040ee094d35c.png)
![iedriverserver flag 02](https://user-images.githubusercontent.com/13453819/36555165-307d9bea-17cf-11e8-988e-7c832181d62b.png)

**Comment by jsakamoto** [comment]
Sorry, I have no time for dealing with this issue.

Could you try to report this issue to Symantec and IEDriver developer team?

**Comment by KevinChrz** [comment]
Whoops, I misread your licencing attribution. I will bring the problem to the IEDriver team!

**Comment by jsakamoto** [comment]
Thanks!
