### ISSUE TITLE
FindElement exception does not fall into catch block. As well as Until exception.

### ISSUE THREAD

**Issue by alexandis** [jsakamoto/nupkg-selenium-webdriver-iedriver#12]
The screenshot explains everything. When exception happens in FindElement or Until methods - it's not caught in my Exception block, even if i use a generic one. I use IEDriver 3.12.0.
![findelement](https://user-images.githubusercontent.com/6149843/41681712-2a4b4a62-74de-11e8-9fe1-a92d248f7a22.png)

**Comment by jsakamoto** [comment]
@alexandis 

Unfortunately, I can't treat this issue because of I'm just packager, not contributor for Selenium IE Driver. 😢

Instead, you can create an issue to official Selenium team's GitHub repository:  
 https://github.com/SeleniumHQ/selenium/issues

I hope this information helps you.

**Comment by alexandis** [comment]
Hi. Ah, ok. Thank you!
