### ISSUE TITLE
Package selenium.iedriver.exe into nuget pkg

### ISSUE THREAD

**Issue by wilsoncg** [jsakamoto/nupkg-selenium-webdriver-iedriver#3]
I've copied the .nupkg file to my corporate network nuget server, but unfortunately my build agent machine doesn't have access to the public internet and so fails to download the IEDriverServer.exe file.

Why not just bundle the IEDriverServer.exe into the contents folder of the .nupkg file? That way the nuget package will work in a corporate network environment with a local nuget server, where not all machines have access to a proxy server or access to the public internet.

See the following issue:
https://nuget.codeplex.com/workitem/4433

**Comment by jsakamoto** [comment]
Thank you for your nice suggestion.

> Why not just bundle the IEDriverServer.exe into the contents folder of the .nupkg file?

Yes, that's right, I understrand what you want to say.

But, I'm not sure that including `IEDriverServer.exe` - this is not my product - in my NuGet package causes **license violation** or not.

I'm still thinking...

Do you have any advice about that causes license violation or not?

P.S.
I have same problem on ChromeDriver: https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/issues/1#issuecomment-69578889

**Comment by wilsoncg** [comment]
It's licensed under the Apache 2.0 license, you are free to redistribute their binaries as long as the Apache 2.0 license is provided. As a courtesy, it's also common to give credit to the original software authors.

In summary, I see no issue with packaging the binary into the nuget package.

**Comment by jsakamoto** [comment]
Thank you fo your reply.

I published beta version of this package that contains IEDriverServer.exe, do not download driver file on the fly.

For more detail, please reference the following issue thread.

https://github.com/jsakamoto/nupkg-selenium-webdriver-iedriver/issues/2#issuecomment-77511706
