### ISSUE TITLE
IE64 Driver Nuget install script error 

### ISSUE THREAD

**Issue by menaheme** [jsakamoto/nupkg-selenium-webdriver-iedriver#7]
Hi 

in line 14 , the script looks for a marker file called `README-IEDriver.txt` but i think it should be
`README-IEDriver64.txt` as its what i see in the project.

Menahem

**Comment by jsakamoto** [comment]
Thank you for your reporting.

But I changed the way to deployment driver file to output path from "install.ps1" PowerShell script to MSBuild task.

Latest release of this package dose not use "README-IEDriver.txt".
