### ISSUE TITLE
Edge driver

### ISSUE THREAD

**Issue by rodchenkov** [jsakamoto/nupkg-selenium-webdriver-iedriver#8]
Hello, thank you for all your work.

Can you please add same nuget package for Edge driver?

Thank you!

**Comment by jsakamoto** [comment]
@rodchenkov Thank you for your post.

Yes, it is already exist here: https://www.nuget.org/packages/Selenium.WebDriver.MicrosoftWebDriver/

The package name and tags doesn't contain the keyword "Edge", but this is exactly WebDriver for Microsoft Edge Web browser ( https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ ).

That package's owner is not me, but I contributed that project: https://github.com/cchitsiang/nuget-selenium-webdriver-microsoftwebdriver/graphs/contributors 

I hope this information helps you.

**Comment by rodchenkov** [comment]
Thank you for your reply

I already tried those package and found that it has problem with asp.net core 1.1 csproj.
I added issue https://github.com/cchitsiang/nuget-selenium-webdriver-microsoftwebdriver/issues/5
