### ISSUE TITLE
Unable to sendkeys on a Wijmo Control grid cell

### ISSUE THREAD

**Issue by mksingh123** [jsakamoto/nupkg-selenium-webdriver-iedriver#9]
Hi,

I am trying to sendkeys on a wijmo control (version: 5.20171.293) cell using the following:
cell.SendKeys(Keys.Control + 'a');

The code gets executed but it does not select all the cells. It works fine with Chrome.
Thanks!

Regards
Manish

**Comment by jsakamoto** [comment]
@mksingh123 

Unfortunately, I can't treat this issue because of I'm just packager, not contributor for Selenium IEDriver. 😢 

Instead, you can create issue here: https://github.com/seleniumhq/selenium/issues/new

I hope this information helps you.

**Comment by mksingh123** [comment]
Thanks @jsakamoto 
I have raised this issue with Selenium
Regards
Manish
